import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose the weights you need
  variable: "--font-poppins", // this enables usage via CSS variable
});

export const metadata: Metadata = {
  title: "bmes demo",
  description: "Generated by krish",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased p-1 lg:p-4`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
